version: '3.9'

services:
  payara:
    image: payara/server-full:latest
    container_name: customer-api
    ports:
      - "8080:8080"
    volumes:
      - ./target/customer-api-1.0-SNAPSHOT.war:/opt/payara/deployments/customer-api.war